### ISSUE TITLE
burnawarefree package EXE?

### ISSUE THREAD

**Issue by hl2guide** [Cossey/chocopackages#1]
Could you please clarify whether your Chocolatey package **burnawarefree** uses the **optional offers installer** or the one that has **no optional offers**?

- offers: https://www.burnaware.com/downloads/burnaware_free_13.1.exe
- no offers: https://www.burnaware.com/downloads/burnaware_cfree_13.1.exe

Ref: https://chocolatey.org/packages/burnawarefree

**Comment by Cossey** [comment]
Good question - its definitely the no offers one (cfree).
